# Generated by Django 5.2.1 on 2025-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_order_options_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='userType',
            field=models.CharField(db_default='customer', max_length=300),
        ),
    ]
