# Generated by Django 5.2.1 on 2025-06-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_customer_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userType',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', help_text='Designates the type of user (e.g., customer, admin).', max_length=50),
        ),
    ]
